# This is a travis-ci.org continuous integration configuration file.
language: node_js
node_js:
  - 12

cache:
  npm: true
  directories:
  - travis_cache


import:
  - credentials.yml
  - .travis-merger.yml


stages:
  - Test
  - Merge

jobs:
  include:
    - stage: Test
      name: travis-freecad-checking

      before_script:
        - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - sudo apt-get update
        - sudo apt-get install -y freecad freecad-python3
        - sudo mkdir /usr/lib/freecad-python3/Mod

      script:
        # use case
        - mkdir .travis
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-freecad-checking/freecad_open_test.py -O .travis/freecad_open_test.py
        - for i in $(find . -name '*.FCStd'); do python3 .travis/freecad_open_test.py $i; done

    - stage: Test
      name: origional-voron-testing
      before_install:
        - chmod +x ./travis_scripts/ci-build.sh
        - npm install remark-cli remark-validate-links

      script: ./travis_scripts/ci-build.sh
